# Generated by Django 2.1.3 on 2018-11-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_auto_20181128_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='veg',
            field=models.BooleanField(default=False),
        ),
    ]
