# Generated by Django 2.1.3 on 2018-11-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0004_auto_20181128_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='kit_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
