# Generated by Django 2.1.3 on 2018-11-30 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regular_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='regularuser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='regularuser',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='regularuser',
            name='password',
        ),
        migrations.AddField(
            model_name='regularuser',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
