# Generated by Django 2.1.3 on 2018-11-30 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regular_user', '0002_auto_20181129_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
